# Analisis de datos

## Formulas a utilizar

* Datos convertidos en VoltajeM
$Datos[V]=(\frac{ValorDato \ast VDIV}{25})-OFST$

* Distancia total del evento
$NroTotal=SARA \ast TDIV \ast 14 $

* Distancia temporal de cada intervalo de eventos
$H.V =2.00E-05 [s]$

* Tiempo Total del Osciloscopio
$TiempoTotal=TDIV \ast 14$

## Lectura de Archivo

In [3]:
#importamos librerias a utilizar
import os
import re
import pandas as pd
import numpy

In [4]:
# lee el contenido del archio de texto donde se esta almacenado
# vectores de almacenamiento
event_data = event = []
contador_evento = contador_suceso = 0
# Character control for identifying headers
caracter_control = "#"
# Capture of empty field values
VDIV = OFST = TDIV = SARA = 0.0
# Capture of text field values
C_VDIV = C_OFST = C_TDIV = C_SARA = ""
# Text values to search in the string
T_VDIV = "VDIV"
T_OFST = "OFST"
T_TDIV = "TDIV"
T_SARA = "SARA"
#manejo de fechas
start_date = end_date = None
T_DATE = r"(Mon|Tue|Wed|Thu|Fri|Sat|Sun) (\w{3}) (\d{1,2}) (\d{2}:\d{2}:\d{2}) ([\+\-]\d{4}) ([\+\-]\d{2}) (\d{4})"

In [7]:
with open('../documentos/DAQ_20K_05.07.22.txt', 'r', encoding='latin1') as file:
    for line in file:
        if line.startswith(caracter_control):
            if "Tue" in line or "Mon" in line or "Wed" in line or "Thu" in line or "Fri" in line or "Sat" in line or "Sun" in line:
                if not start_date:
                    start_date=line.strip().split('#')[1]                    
                else:
                    end_date=line.strip().split('#')[1]                    
            contador_evento += 1
            event = []

            # Check if the line contains all required text values
            if all(text in line for text in [T_VDIV, T_OFST, T_TDIV, T_SARA]):
                cadena = line.split(' ')
                # Separate text data from the header
                for i, word in enumerate(cadena):
                    if word.endswith(T_VDIV):
                        C_VDIV = float(cadena[i + 1].split('V')[0])
                    elif word.endswith(T_OFST):
                        C_OFST = float(cadena[i + 1].split('V')[0])
                    elif word.endswith(T_TDIV):
                        C_TDIV = float(cadena[i + 1].split('S')[0])
                    elif word.endswith(T_SARA):
                        C_SARA = float(cadena[i + 1].split('Sa/s')[0])
        elif re.match(re.compile(r'^\-?[1-9][0-9]*$'), line):
            event.append(int(line))
        elif len(line.strip()) == 0 and contador_suceso == 0:
            total_event = C_SARA * C_TDIV * 14
            if len(event) != int(total_event):
                event += [0] * (int(total_event) - len(event))
            else:
                print(len(line))
            contador_suceso += 1
            event_data.append(event)
        else:
            contador_suceso = 0  # Comment explaining the purpose of this line

In [8]:
C_VDIV

0.1

In [9]:
 C_OFST

0.28

In [10]:
 C_TDIV

2e-08

In [11]:
C_SARA

1000000000.0

In [12]:
print(start_date)

 Tue Apr 26 00:57:17 -0400 -04 2022

In [13]:
print(end_date)

 Thu Apr 28 04:40:47 -0400 -04 2022

In [14]:
l_df=pd.DataFrame(event_data).transpose()
#l_df.to_csv(\"dataset.csv\",index=False,header=True)

In [15]:
l_df

,0,1,2,3,4,5,6,7,8,9,...,10998,10999,11000,11001,11002,11003,11004,11005,11006,11007
0,70,70,69,71,70,70,70,70,70,71,...,69,70,53,-125,69,69,70,70,69,69
1,71,70,70,70,70,70,69,70,71,70,...,70,69,53,-125,71,70,70,70,69,70
2,70,70,70,70,70,71,70,69,70,70,...,70,69,55,-125,70,69,70,70,70,69
3,70,70,70,69,70,71,69,71,71,70,...,70,70,58,-125,70,69,69,70,70,71
4,70,70,70,69,70,70,70,70,70,70,...,70,70,58,-125,71,71,69,69,69,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,70,70,69,69,70,69,69,69,69,70,...,69,70,70,0,69,69,69,70,70,70
276,70,71,69,69,70,69,69,70,70,70,...,70,71,70,0,69,69,69,69,69,70
277,70,71,70,0,70,70,70,69,70,69,...,70,70,71,0,69,69,70,71,70,70
278,69,70,70,0,69,70,69,70,69,0,...,0,70,71,0,0,71,69,70,70,71
279,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
# especificando la direccion de archivo a guardar
ruta_csv = '../documentos/datos.csv'

In [18]:
# Guarda el DataFrame en un archivo CSV
l_df.to_csv(ruta_csv, index=False)

## Conversion de datos

In [19]:
data=l_df
data

,0,1,2,3,4,5,6,7,8,9,...,10998,10999,11000,11001,11002,11003,11004,11005,11006,11007
0,70,70,69,71,70,70,70,70,70,71,...,69,70,53,-125,69,69,70,70,69,69
1,71,70,70,70,70,70,69,70,71,70,...,70,69,53,-125,71,70,70,70,69,70
2,70,70,70,70,70,71,70,69,70,70,...,70,69,55,-125,70,69,70,70,70,69
3,70,70,70,69,70,71,69,71,71,70,...,70,70,58,-125,70,69,69,70,70,71
4,70,70,70,69,70,70,70,70,70,70,...,70,70,58,-125,71,71,69,69,69,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,70,70,69,69,70,69,69,69,69,70,...,69,70,70,0,69,69,69,70,70,70
276,70,71,69,69,70,69,69,70,70,70,...,70,71,70,0,69,69,69,69,69,70
277,70,71,70,0,70,70,70,69,70,69,...,70,70,71,0,69,69,70,71,70,70
278,69,70,70,0,69,70,69,70,69,0,...,0,70,71,0,0,71,69,70,70,71
279,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0